import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Git worktrees are independent checkouts and may contain generated builds.
    ".worktrees/**",
    // Generated by `supabase start`; this is bundled runtime code, not source.
    "supabase/.temp/**",
    // Disposable database sandboxes and verification builds are not application source.
    "work/**",
    ".tmp/**",
    // Generated from the checked Calendar worker entry point.
    "supabase/functions/calendar-worker/index.js",
  ]),
]);

export default eslintConfig;
