"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import { buildStartupCalendar, isMentorHighlighted, rankAvailableMentors, type StartupCalendarCell } from "@/src/mentor-booking/startup-calendar";
import { currentCalendarWeek, startupBookingSlots, type StartupBookingSlot } from "@/src/mentor-booking/startup-availability";
import type { MentorBookingWorkspaceResponse } from "@/src/mentor-booking/types";
import { formatAvailabilityTimeLabel } from "./presentation";

const WEEKDAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] as const;
const TIME_ROWS = Array.from({ length: 53 }, (_, index) => { const minutes = 8 * 60 + index * 15; return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; });

function dateKey(value: string, timeZone: string): string { return new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)); }
function timeKey(value: string, timeZone: string): string { return new Intl.DateTimeFormat("en-US", { timeZone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)); }
function addDays(date: string, days: number): string { const next = new Date(`${date}T12:00:00Z`); next.setUTCDate(next.getUTCDate() + days); return next.toISOString().slice(0, 10); }
function weekStart(date: string): string { return addDays(date, -new Date(`${date}T12:00:00Z`).getUTCDay()); }
function dayHeading(date: string): string { return new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }

export function StartupAvailabilityBrowser({ acting, data, onRequest }: { acting: boolean; data: MentorBookingWorkspaceResponse; onRequest: (slot: StartupBookingSlot, topic: string) => void }) {
  const [mentorQuery, setMentorQuery] = useState("");
  const [dialogQuery, setDialogQuery] = useState("");
  const [selectedCell, setSelectedCell] = useState<StartupCalendarCell | null>(null);
  const [selectedMentorId, setSelectedMentorId] = useState<string | null>(null);
  const [topic, setTopic] = useState("");
  const [weekOffset, setWeekOffset] = useState(0);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const [now, setNow] = useState(() => new Date());
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 60_000); return () => window.clearInterval(timer); }, []);
  const slots = useMemo(() => startupBookingSlots({ availability: data.availability ?? [], acceptedOccupancy: data.acceptedOccupancy, semesterStartDate: data.semesterStartDate, semesterEndDate: data.semesterEndDate, timeZone: data.timeZone, now, weekOffset }), [data, now, weekOffset]);
  const calendar = useMemo(() => buildStartupCalendar({ slots, timeZone: data.timeZone }), [data.timeZone, slots]);
  const actualWeek = useMemo(() => currentCalendarWeek(now, data.timeZone), [data.timeZone, now]);
  const selectedWeek = useMemo(() => currentCalendarWeek(now, data.timeZone, weekOffset), [data.timeZone, now, weekOffset]);
  const dates = selectedWeek.dates;
  const semesterLastWeek = weekStart(data.semesterEndDate);
  const maxWeekOffset = Math.max(0, Math.round((Date.parse(`${semesterLastWeek}T12:00:00Z`) - Date.parse(`${actualWeek.startDate}T12:00:00Z`)) / (7 * 24 * 60 * 60 * 1000)));
  const cellByPosition = useMemo(() => new Map(calendar.cells.map((cell) => [`${dateKey(cell.startsAt, data.timeZone)}/${timeKey(cell.startsAt, data.timeZone)}`, cell])), [calendar.cells, data.timeZone]);
  const visibleCells = useMemo(() => calendar.cells.filter((cell) => { const date = dateKey(cell.startsAt, data.timeZone); return date >= selectedWeek.startDate && date <= selectedWeek.endDate; }), [calendar.cells, data.timeZone, selectedWeek.endDate, selectedWeek.startDate]);
  const topMentors = useMemo(() => {
    const mentors = new Map(visibleCells.flatMap((cell) => cell.mentors).map((mentor) => [mentor.profileId, mentor]));
    return rankAvailableMentors({ mentors: [...mentors.values()], startupNeeds: data.viewer.startupNeeds ?? [] }).slice(0, 3);
  }, [data.viewer.startupNeeds, visibleCells]);
  const rankedMentors = useMemo(() => selectedCell ? rankAvailableMentors({ mentors: selectedCell.mentors, startupNeeds: data.viewer.startupNeeds ?? [] }).filter((mentor) => mentor.name.toLocaleLowerCase().includes(dialogQuery.trim().toLocaleLowerCase())) : [], [data.viewer.startupNeeds, dialogQuery, selectedCell]);
  const selectedMentor = rankedMentors.find((mentor) => mentor.profileId === selectedMentorId) ?? rankedMentors[0] ?? null;

  function closeDialog() { setSelectedCell(null); setSelectedMentorId(null); setDialogQuery(""); setTopic(""); queueMicrotask(() => triggerRef.current?.focus()); }
  useEffect(() => { if (!selectedCell) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") closeDialog(); }; document.addEventListener("keydown", onKeyDown); return () => document.removeEventListener("keydown", onKeyDown); }, [selectedCell]);
  function selectCell(cell: StartupCalendarCell, trigger: HTMLButtonElement) { triggerRef.current = trigger; setSelectedCell(cell); setSelectedMentorId(rankAvailableMentors({ mentors: cell.mentors, startupNeeds: data.viewer.startupNeeds ?? [] })[0]?.profileId ?? null); }
  function requestSelectedTime() { if (!selectedCell || !selectedMentor || !topic.trim()) return; const matched = slots.find((slot) => slot.startsAt === selectedCell.startsAt && slot.mentor.profileId === selectedMentor.profileId); if (matched) onRequest(matched, topic.trim()); }

  return <section className="mt-5" aria-label="Browse mentor availability">
    <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold text-[#002147]">Choose a time that works</h2><p className="mt-1 text-sm text-slate-600">Start with this real-world calendar week, then move forward to book later dates.</p></div><label className="text-sm font-medium text-[#002147]">Find a mentor<input type="search" value={mentorQuery} onChange={(event) => setMentorQuery(event.target.value)} placeholder="Highlight a mentor" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-normal sm:w-auto" /></label></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-slate-200 pt-4"><button type="button" aria-label="Previous week" disabled={weekOffset === 0} onClick={() => setWeekOffset((value) => Math.max(0, value - 1))} className="grid size-9 place-items-center rounded-lg border border-slate-300 bg-white text-[#002147] disabled:cursor-not-allowed disabled:opacity-35"><ChevronLeft size={18} /></button><div className="text-center"><p className="text-xs font-medium text-slate-500">{weekOffset === 0 ? "Current week" : "Available week"}</p><p className="text-lg font-semibold text-[#002147]">{selectedWeek.label}</p></div><button type="button" aria-label="Next week" disabled={weekOffset >= maxWeekOffset} onClick={() => setWeekOffset((value) => Math.min(maxWeekOffset, value + 1))} className="grid size-9 place-items-center rounded-lg border border-slate-300 bg-white text-[#002147] disabled:cursor-not-allowed disabled:opacity-35"><ChevronRight size={18} /></button></div></div>
    {topMentors.length > 0 && <details className="mt-4 rounded-xl border border-slate-200 bg-white"><summary className="cursor-pointer px-4 py-3 font-semibold text-[#002147] marker:text-sky-700">Top mentor matches <span className="ml-2 text-sm font-normal text-slate-500">({topMentors.length})</span></summary><div className="grid gap-2 border-t border-slate-200 p-3 sm:grid-cols-3">{topMentors.map((mentor, index) => <button type="button" key={mentor.profileId} onClick={() => setMentorQuery(mentor.name)} className="rounded-lg border border-slate-200 p-3 text-left hover:border-sky-400 hover:bg-sky-50"><span className="block text-xs font-semibold uppercase tracking-wide text-sky-700">#{index + 1}</span><span className="mt-1 block font-semibold text-[#002147]">{mentor.name}</span><span className="mt-1 block text-xs text-slate-600">{mentor.matchCount > 0 ? `Matches ${mentor.matchCount} of your needs` : "Available this week"}</span></button>)}</div></details>}
    {visibleCells.length === 0 && <p className="mt-4 rounded-xl border border-dashed border-slate-300 px-4 py-3 text-center text-sm text-slate-600">No mentor availability is open during this week. Try the next week.</p>}
    <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 bg-white p-3" aria-label="Mentor availability calendar"><div className="grid min-w-[40rem] grid-cols-[5rem_repeat(7,minmax(5rem,1fr))] gap-px overflow-hidden rounded-lg bg-slate-200 text-xs"><div className="bg-slate-50 p-2 font-semibold text-slate-500">Time</div>{dates.map((date, index) => <div key={date} aria-label={`${WEEKDAY_NAMES[index]} ${date}`} className="bg-slate-50 p-2 text-center font-semibold text-[#002147]">{dayHeading(date)}</div>)}{TIME_ROWS.flatMap((time) => [<div key={`${time}-label`} className="min-h-10 whitespace-nowrap bg-slate-50 p-2 text-slate-500">{formatAvailabilityTimeLabel(time)}</div>, ...dates.map((date) => { const cell = cellByPosition.get(`${date}/${time}`); const highlighted = cell ? isMentorHighlighted(cell, mentorQuery) : false; return <button key={`${date}/${time}`} type="button" disabled={!cell} onClick={(event) => cell && selectCell(cell, event.currentTarget)} aria-label={cell ? `${date} at ${time}; ${cell.mentors.length} mentor${cell.mentors.length === 1 ? "" : "s"} available` : `${date} at ${time}; unavailable`} className={`relative min-h-10 touch-none border-0 ${cell ? highlighted ? "bg-sky-300 ring-2 ring-inset ring-sky-600 hover:bg-sky-400" : "bg-sky-100 hover:bg-sky-200" : "bg-white"}`}>{cell && <span className="absolute inset-0 grid place-items-center font-semibold text-[#002147]">{cell.mentors.length} mentor{cell.mentors.length === 1 ? "" : "s"}</span>}</button>; })])}</div></div>
    {selectedCell && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#002147]/45 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) closeDialog(); }}><section role="dialog" aria-modal="true" aria-labelledby="booking-picker-title" className="w-full max-w-xl rounded-2xl border border-sky-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-sky-700">Open time</p><h2 id="booking-picker-title" className="mt-1 text-xl font-semibold text-[#002147]">{new Intl.DateTimeFormat("en-US", { timeZone: data.timeZone, weekday: "long", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(selectedCell.startsAt))}</h2><p className="mt-1 text-sm text-slate-600">Choose a mentor available at this time.</p></div><button type="button" onClick={closeDialog} className="rounded-md px-2 py-1 text-sm font-semibold text-slate-600 hover:bg-slate-100" aria-label="Close mentor picker">Close</button></div><label className="mt-4 block text-sm font-medium text-[#002147]">Search mentors<input autoFocus type="search" value={dialogQuery} onChange={(event) => setDialogQuery(event.target.value)} placeholder="Search available mentors" className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><div className="mt-3 max-h-52 space-y-2 overflow-y-auto">{rankedMentors.map((mentor) => <button type="button" key={mentor.profileId} onClick={() => setSelectedMentorId(mentor.profileId)} className={`w-full rounded-lg border p-3 text-left ${selectedMentor?.profileId === mentor.profileId ? "border-sky-500 bg-sky-50" : "border-slate-200 hover:border-sky-300"}`}><span className="font-semibold text-[#002147]">{mentor.name}</span>{mentor.matchCount > 0 ? <span className="ml-2 text-xs font-medium text-emerald-700">Matches {mentor.matchCount} of your needs</span> : <span className="ml-2 text-xs text-slate-500">Available at this time</span>}</button>)}{rankedMentors.length === 0 && <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-600">No available mentor matches that name.</p>}</div><label className="mt-4 block text-sm font-medium text-[#002147]">Topic<input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="What would you like to discuss?" className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={closeDialog} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Cancel</button><button type="button" disabled={acting || !selectedMentor || !topic.trim()} onClick={requestSelectedTime} className="rounded-lg bg-[#002147] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Request this time</button></div></section></div>}
  </section>;
}
