alter table public.mentor_weekly_availability enable row level security;
create policy "active participants and admins read mentor weekly availability" on public.mentor_weekly_availability for select to authenticated using (private.can_manage_semester(semester_id,auth.uid()) or exists(select 1 from public.semester_memberships membership where membership.semester_id=mentor_weekly_availability.semester_id and membership.profile_id=private.current_profile_id() and membership.role in ('mentor','startup') and membership.status='active'));
create policy "owning mentors manage weekly availability" on public.mentor_weekly_availability for all to authenticated using (mentor_semester_id in (select term.id from public.mentor_semesters term join public.semester_memberships membership on membership.id=term.semester_membership_id where term.semester_id=mentor_weekly_availability.semester_id and membership.profile_id=private.current_profile_id() and membership.role='mentor' and membership.status='active')) with check (mentor_semester_id in (select term.id from public.mentor_semesters term join public.semester_memberships membership on membership.id=term.semester_membership_id where term.semester_id=mentor_weekly_availability.semester_id and membership.profile_id=private.current_profile_id() and membership.role='mentor' and membership.status='active'));
revoke all on table public.mentor_weekly_availability from anon,authenticated;
grant select on table public.mentor_weekly_availability to authenticated;
revoke all on function public.replace_mentor_weekly_availability(uuid,jsonb) from public,anon;
revoke all on function public.request_mentor_booking(uuid,uuid,timestamptz,timestamptz,text) from public,anon;
revoke execute on function public.replace_mentor_weekly_availability(uuid,jsonb) from authenticated;
grant execute on function public.request_mentor_booking(uuid,uuid,timestamptz,timestamptz,text) to authenticated;

alter table public.mentor_booking_accepted_occupancy enable row level security;
create policy "active participants and admins read accepted booking occupancy" on public.mentor_booking_accepted_occupancy for select to authenticated using (private.can_manage_semester(semester_id,auth.uid()) or exists(select 1 from public.semester_memberships membership where membership.semester_id=mentor_booking_accepted_occupancy.semester_id and membership.profile_id=private.current_profile_id() and membership.role in ('mentor','startup') and membership.status='active'));
create policy "owning mentors create accepted booking occupancy" on public.mentor_booking_accepted_occupancy for insert to authenticated with check (exists(select 1 from public.mentor_booking_requests request where request.id=mentor_booking_accepted_occupancy.request_id and request.semester_id=mentor_booking_accepted_occupancy.semester_id and request.mentor_semester_id=mentor_booking_accepted_occupancy.mentor_semester_id and request.starts_at=mentor_booking_accepted_occupancy.starts_at and request.ends_at=mentor_booking_accepted_occupancy.ends_at and request.status='accepted' and request.mentor_profile_id=private.current_profile_id()));
create policy "booking parties release cancelled booking occupancy" on public.mentor_booking_accepted_occupancy for delete to authenticated using (exists(select 1 from public.mentor_booking_requests request where request.id=mentor_booking_accepted_occupancy.request_id and request.semester_id=mentor_booking_accepted_occupancy.semester_id and request.status='cancelled' and (request.mentor_profile_id=private.current_profile_id() or exists(select 1 from public.startup_team_memberships team join public.semester_memberships membership on membership.id=team.semester_membership_id and membership.semester_id=team.semester_id where team.semester_id=request.semester_id and team.startup_semester_id=request.startup_semester_id and membership.profile_id=private.current_profile_id() and membership.role='startup' and membership.status='active'))));
revoke all on table public.mentor_booking_accepted_occupancy from anon,authenticated;
grant select,insert,delete on table public.mentor_booking_accepted_occupancy to authenticated;
