"use client";
import { Upload } from "lucide-react";
import { useState } from "react";
import { outreachFetch } from "./authenticated-fetch";
import styles from "../outreach-workspace.module.css";
type Row = { id: string; name: string; issue: string; decision: "create" | "merge" | "exclude" };
export function ImportReview({ preview = false, semesterId = "" }: { preview?: boolean; semesterId?: string }) {
 const [rows,setRows]=useState<Row[]>([]); const [importId,setImportId]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 async function upload(file:File){setBusy(true);try{const lines=(await file.text()).split(/\r?\n/u).filter(Boolean);const headers=(lines.shift()??"").split(",");const parsed=lines.slice(0,250).map(line=>Object.fromEntries(line.split(",").map((v,i)=>[headers[i]??`column_${i}`,v.trim()])));const response=await outreachFetch("/api/admin/outreach/imports/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({semesterId,source:"csv",sourceFilename:file.name,rows:parsed})});const result=await response.json() as {importId?:string;rows?:Row[];error?:{message?:string}};if(!response.ok||!result.importId||!result.rows)throw new Error(result.error?.message??"Preview failed.");setImportId(result.importId);setRows(result.rows);setMessage("Preview staged.");}catch(error){setMessage(error instanceof Error?error.message:"Preview failed.")}finally{setBusy(false)}}
 async function commit(){if(!importId)return;setBusy(true);try{const response=await outreachFetch(`/api/admin/outreach/imports/${importId}/commit`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":importId},body:JSON.stringify({semesterId,importId})});if(!response.ok)throw new Error("Commit failed.");setMessage("Import committed successfully.")}catch(error){setMessage(error instanceof Error?error.message:"Commit failed.")}finally{setBusy(false)}}
 if(!preview)return <section className={styles.importReview}><h2>Import contacts safely</h2><p>Select a CSV file to stage rows for review. Use the sample template to see the supported headers and example values.</p><div className={styles.controlRow}><a className={styles.secondaryButton} href="/templates/outreach-import-template.csv" download>Download sample CSV</a><label className={styles.primaryButton}><Upload size={16}/> Choose file<input hidden type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></label></div>{message&&<p className={styles.unavailable}>{message}</p>}</section>;
 return <section className={styles.importReview}><h2>Review every row before committing</h2>{message&&<p className={styles.unavailable}>{message}</p>}<div className={styles.resolutions}>{rows.map((row,index)=><div className={styles.resolution} key={row.id}><strong>{row.name}</strong><p>{row.issue||"Ready"}</p><select value={row.decision} onChange={e=>setRows(prev=>prev.map((item,i)=>i===index?{...item,decision:e.target.value as Row["decision"]}:item))}><option value="create">Create new</option><option value="merge">Merge</option><option value="exclude">Exclude</option></select></div>)}</div><button className={styles.primaryButton} disabled={busy||!importId} onClick={()=>void commit()}>Commit reviewed rows</button></section>;
}
